config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get "auth" => "session#new", as: :auth
  post "auth" => "session#create"
  delete "auth"=> "session#destroy", as: :sign_out 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    response = Http.get("http://localhost:3000/skeletons.json")
  @user_name = session[:user_name] 
   @skeletons = JSON.parse response
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create

    http_response = Http.post("http://localhost:3000/auth.json", json: {email: params[:session][:email], password: params[:session][:password]})

    if http_response.code == 201
      user = JSON.parse(http_response)
      session[:user_name] = user["user_name"]
      session[:token] = user["token"]
      redirect_to root_path
    else
      flash.now[:alert] = "Auth failed Bro"
      render :new
    end
  end

  def destroy
    session.delete(:user_name)
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SkeletonFrontEnd</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
<div>
  <% if @user_name.nil? %>
    <%= link_to "Sign In", auth_path %>
  <% else %>
    <%= link_to "Sign Out", sign_out_path, method: :delete %>
  <% end %>
</div>

<div>
    <%@skeletons.each do |skeleton|%>
    <li><%= skeleton["content"] %><p>Posted by<%= skeleton["user"]["user_name"] %></p></li>
    <% end %>
</div>

app/views/session/new.html.erb
<div class="row">
     <div class="page-header col-xs-8 col-xs-offset-2">
       <h1>Sign In!</h1>
     </div>
   </div>
   <div class="row">
     <%= simple_form_for :session, url: :auth  do |f| %>
       <div class= "col-xs-8 col-xs-offset-2">
         <%= f.input :email, label:false, placeholder: "Email"%>
         <%= f.input :password, label:false, placeholder:"Password" %>
         <%= f.submit "Log In", class: "btn btn-primary" %>
       </div>
     <% end %>
   </div>